const fs = require('fs');
const { execFileSync } = require('child_process');
const W = __dirname, S = W + '/salida';
const R = '/Users/usuario/Proyectos/chispa-video/videos';
const E = '/Users/usuario/Desktop/SOLERS - PROGRAMAS/VIDEOS CHISPA';
const FF = '/Users/usuario/herramientas/bin/ffmpeg';
const cp = (a, b) => { fs.copyFileSync(a, b); console.log('→', b, (fs.statSync(b).size / 1e6).toFixed(1), 'MB'); };
cp(`${S}/chispa-corto.mp4`, `${R}/chispa-corto-redes.mp4`);
cp(`${S}/chispa-largo.srt`, `${R}/chispa-explicativo.srt`);
cp(`${S}/chispa-corto.srt`, `${R}/chispa-corto-redes.srt`);
execFileSync('python3', [`${W}/gen-guion.py`, `${R}/GUION.md`], { stdio: 'inherit' });
execFileSync(FF, ['-v', 'error', '-y', '-ss', '4', '-i', `${S}/chispa-largo.mp4`, '-frames:v', '1', '-q:v', '3', `${R}/chispa-explicativo-portada.jpg`]);
execFileSync(FF, ['-v', 'error', '-y', '-ss', '3', '-i', `${S}/chispa-corto.mp4`, '-frames:v', '1', '-q:v', '3', `${R}/chispa-corto-portada.jpg`]);
cp(`${S}/chispa-largo.mp4`, `${E}/Chispa - video explicativo completo (1080p).mp4`);
cp(`${R}/chispa-explicativo.mp4`, `${E}/Chispa - video explicativo (version ligera).mp4`);
cp(`${S}/chispa-corto.mp4`, `${E}/Chispa - corte para redes (90 s).mp4`);
cp(`${S}/chispa-largo.srt`, `${E}/Chispa - video explicativo.srt`);
cp(`${S}/chispa-corto.srt`, `${E}/Chispa - corte para redes.srt`);
cp(`${R}/GUION.md`, `${E}/GUION - videos Chispa.md`);
