// Guion del vídeo largo de Chispa (≈ 9 min, 18 secciones). Cada escena: ctx (a visitante / b negocio de
// prueba con sesión / c navegador limpio para el alta), rótulo y frases (t = lo que se oye y se subtitula;
// voz = cómo se le dice a la voz si hace falta otra pronunciación; a = lo que se hace en pantalla).
const { PREGEN, card, esperarImagenIA, grabarVideo, reproducirVideo } = require('./comun');

const PORTADA = `<div class="bolt">⚡</div><h1><span>Chispa</span></h1><p>Tu marketing en automático</p>
<p style="font-size:20px;color:#9aa3b5;margin-top:10px">Guía paso a paso · para negocios y creadores, en cualquier idioma</p>
<div class="pie">Ejemplos: El Paraíso (bar restaurante, Palma) y un café de prueba creado para este vídeo</div>`;
const CIERRE = `<div class="bolt">⚡</div><h1>Tú atiendes tu negocio.<br><span>Chispa llena tus redes.</span></h1>
<p>Pruébalo 14 días gratis, sin tarjeta</p><div class="url">solers-es.github.io/chispa-demo</div>
<div class="pie">Una herramienta de Solers</div>`;
const cardTxt = (h, t) => h.p.locator('#main .card', { hasText: t }).first();

module.exports = {
  escenas: [
    {
      id: 'portada', entrada: 300,
      preparar: async h => { await h.v(() => vista('landing')); await h.v(() => window.__V.cursorVisible(false)); await h.tarjeta(PORTADA); await h.esperar(900); },
      segs: [
        { t: 'Esto es Chispa: tu marketing en automático. En unos minutos te enseño, paso a paso, todo lo que hace, con todo lo nuevo de esta versión.' },
        { t: 'Los ejemplos son El Paraíso, un bar restaurante de Palma, y un café de prueba que hemos creado para este vídeo.', pausa: 0.6 },
      ],
      despues: async h => { await h.quitarTarjeta(); await h.v(() => window.__V.cursorVisible(true)); },
    },
    {
      id: 'que-es', rotulo: ['1', 'Qué es Chispa', 'Para negocios y creadores, en cualquier idioma'],
      preparar: async h => { await h.v(() => { vista('landing'); window.scrollTo(0, 0); }); await h.mover(720, 520, 10); },
      segs: [
        { t: 'Chispa es un asistente con inteligencia artificial que lleva el marketing de tu negocio: escribe tus publicaciones, crea las imágenes, las programa y te ayuda a contestar a tus clientes.',
          a: async h => { await h.esperar(1200); await h.resaltar('#landing h1', 2400); await h.mover(700, 600); await h.scrollSuave(null, 640); } },
        { t: 'Sirve para cualquier negocio de cara al público, un bar, una peluquería, un gimnasio o una tienda, y también para creadores de contenido.',
          a: async h => { await h.mover(500, 420); await h.esperar(900); await h.mover(1000, 560); } },
        { t: 'Y trabaja en el idioma que quieras: español, inglés, alemán, francés… el que hablen tus clientes.',
          a: async h => { await h.scrollSuave(null, 0); await h.apuntar('#alHero'); } },
      ],
    },
    {
      id: 'alta', ctx: 'c', rotulo: ['2', 'Darse de alta', '14 días gratis, sin tarjeta'],
      preparar: async h => { await h.v(() => { vista('landing'); window.scrollTo(0, 0); }); await h.mover(720, 300, 10); },
      segs: [
        { t: 'Darse de alta es cosa de un minuto. Pulsas «Empieza gratis 14 días».', voz: 'Darse de alta es cosa de un minuto. Pulsas «Empieza gratis catorce días».',
          a: async h => { await h.clic('#alHero', { despues: 1200 }); } },
        { t: 'Escribes el nombre de tu negocio, tocas a qué te dedicas, y eliges el idioma de tus publicaciones.',
          a: async h => { await h.escribir('#alNom', 'Café Aurora (ejemplo)', 60); await h.clic('#alSecs .al-sec[data-s="cafeteria"]', { despues: 600 }); await h.resaltar('#alIdi', 1400); } },
        { t: 'Pones tu correo y eliges plan: Básico, 39 € al mes; Pro, 79 €; y Agencia, 149 €. Más IVA.',
          voz: 'Pones tu correo y eliges plan: Básico, treinta y nueve euros al mes; Pro, setenta y nueve; y Agencia, ciento cuarenta y nueve. Más IVA.',
          a: async h => { await h.escribir('#alCor', 'cafe.aurora.video@example.com', 30); await h.verEn('#alPlanes'); await h.resaltar('#alPlanes .al-plan[data-p="basico"]', 1300); await h.resaltar('#alPlanes .al-plan[data-p="pro"]', 1100); await h.resaltar('#alPlanes .al-plan[data-p="agencia"]', 1100); } },
        { t: 'Los 14 días de prueba son gratis, sin tarjeta y sin permanencia.', voz: 'Los catorce días de prueba son gratis, sin tarjeta y sin permanencia.',
          a: async h => { await h.clic('#alPlanes .al-plan[data-p="pro"]', { despues: 400 }); await h.clic('#alAcepto', { despues: 400 }); } },
        { t: 'Pulsas «Crear mi Chispa gratis», y en unos segundos tu Chispa está lista, con todo lo de tu sector ya puesto.',
          a: async h => { await h.clic('#alBtn', { despues: 500 }); await h.p.waitForSelector('#alCod', { timeout: 25000 }).catch(() => console.log('   ! no salió la pantalla de alta lista')); await h.esperar(600); await h.mover(720, 300); } },
        { t: 'Te da un código de acceso: es tu llave para entrar desde cualquier aparato. Guárdalo y no se lo enseñes a nadie; por eso aquí sale tapado.',
          a: async h => { await h.resaltar('#alCod', 2600); await h.apuntar('button:has-text("Entrar en mi Chispa")'); await h.resaltar('button:has-text("Entrar en mi Chispa")', 1500); }, pausa: 0.6 },
      ],
    },
    {
      id: 'mi-negocio', rotulo: ['3', 'Mi negocio', 'Tus datos, tu sector y tu idioma'],
      preparar: async h => { await h.cerrarTodo(); await h.panel('asistente'); },
      segs: [
        { t: 'En «Mi negocio» están los datos que Chispa usa en cada publicación: el nombre, la dirección, la web, la carta y las reservas.',
          a: async h => { await h.pestana('Mi negocio'); await h.esperar(500); await h.resaltar(cardTxt(h, 'Ficha completa'), 2200); } },
        { t: 'Para rellenarlo no hace falta escribir: pegas cualquier enlace, de tu Instagram, tu web o tu ficha de Google, y Chispa lo coloca en su sitio.',
          a: async h => { await h.verEn('#main >> text=Rellénalo en un momento'); await h.resaltar(cardTxt(h, 'Rellénalo en un momento'), 2600); } },
        { t: 'Aquí está tu tipo de negocio. Con él, Chispa sabe qué botones poner, qué ideas proponerte y a qué horas publicar.',
          a: async h => { await h.verEn('#main >> text=Tipo de negocio'); await h.resaltar(cardTxt(h, 'Tipo de negocio'), 2800); } },
        { t: 'Y este es el idioma de tu contenido. Puede ser cualquiera: si tus clientes son turistas, Chispa les escribe en su idioma.',
          a: async h => { await h.verEn('#main >> text=Idioma del contenido'); await h.resaltar(cardTxt(h, 'Idioma del contenido'), 2800); } },
      ],
    },
    {
      id: 'conexiones', ctx: 'b', rotulo: ['4', 'Conexiones', 'Una vez, y vale para todos tus aparatos'],
      preparar: async h => { await h.cerrarTodo(); await h.panel('asistente'); },
      segs: [
        { t: 'En «Conexiones» unes tus redes: Instagram y Facebook, tu ficha de Google, YouTube y TikTok.',
          a: async h => { await h.pestana('Conexiones'); await h.esperar(600); await h.resaltar('#chispaSyncCard', 2600); } },
        { t: 'Tu negocio vive en el servidor de Chispa: entras una vez en cada aparato, y lo que conectas vale para todos, el móvil, la tablet y el ordenador.',
          a: async h => { await h.resaltar('#chispaSyncCard h3', 2600); await h.mover(900, 330); } },
        { t: 'Debajo tienes una guía, paso a paso, para dejarlo todo listo en cinco minutos.',
          a: async h => { await h.verEn('#main >> text=Haz estos pasos una sola vez', 'start'); await h.v(() => window.scrollBy({ top: -120, behavior: 'smooth' })); await h.mover(760, 520); await h.rueda(500, 14, 1600); } },
        { t: 'Y una cosa clara: cuando conectes tus cuentas y cada red dé su permiso, se publica solo. Hasta entonces, Chispa te lo deja todo preparado para subirlo con un toque.',
          a: async h => { await h.scrollSuave(null, 0); await h.apuntar('#chispaSyncCard button:has-text("Conectar")'); await h.resaltar('#chispaSyncCard button:has-text("Conectar")', 2000); }, pausa: 0.6 },
      ],
    },
    {
      id: 'crear', ctx: 'b', rotulo: ['5', 'Crear una publicación', 'Texto, imagen con IA, idiomas y reaprovechar'],
      preparar: async h => { await h.cerrarTodo(); await h.panel('asistente'); await h.esperar(800); },
      segs: [
        { t: 'Ahora, lo principal: crear una publicación. Le escribes la idea en una frase.',
          a: async h => { await h.escribir('#idea', 'Tarta de zanahoria casera con café de especialidad', 55); } },
        { t: 'Pulsas «Que Chispa lo escriba», y te prepara cuatro versiones, cada una con un enfoque distinto.',
          a: async h => { await h.clic('button:has-text("Que Chispa lo escriba")', { despues: 2500 }); await h.verEn(card(0), 'start'); await h.v(() => window.scrollBy({ top: -80, behavior: 'smooth' })); await h.mover(900, 420); } },
        { t: 'Y la imagen la crea la inteligencia artificial, de verdad: pulsas «Otra versión», y la pinta a partir de tu texto.',
          a: async h => { await h.clic(`${card(0)} .cm-acts button >> nth=0`, { despues: 600 }); await h.v(() => document.querySelector('#cmCard_0').scrollIntoView({ behavior: 'smooth', block: 'start' })); await esperarImagenIA(h); await h.esperar(500); } },
        { t: 'Encima lleva el sello de tu marca, con tu nombre, y debajo los botones que tu cliente puede pulsar.',
          a: async h => { await h.v(() => { document.querySelector('#cmCard_0').scrollIntoView({ block: 'start' }); window.scrollBy(0, -80); }); await h.zoom(`${card(0)} .cm-media`, 1.3); await h.esperar(2600); await h.sinZoom(); } },
        { t: 'Con «Otros idiomas» la traduce. Por ejemplo, al inglés y al alemán, juntos en la misma publicación.',
          a: async h => { await h.clic(`${card(0)} button:has-text("Otros idiomas")`, { despues: 900 }); await h.clic('#modalBox button:has-text("Traducir")', { despues: 500 }); await h.p.waitForFunction(() => /🇬🇧/.test((document.getElementById('ciaTradRes') || {}).innerText || ''), null, { timeout: 30000 }).catch(() => { }); await h.verEn('#ciaTradRes'); await h.resaltar('#ciaTradRes', 2200); } },
        { t: 'Y si tienes un texto largo, un artículo o el guion de un vídeo, «Reaprovechar» lo convierte en varias publicaciones, para cada red.',
          a: async h => { await h.cerrarTodo(); await h.scrollSuave(null, 0); await h.clic('#main button:has-text("Reaprovechar")', { despues: 900 }); await h.resaltar('#modalBox', 2400); }, pausa: 0.6 },
      ],
      despues: async h => { await h.cerrarTodo(); },
    },
    {
      id: 'video', ctx: 'b', rotulo: ['6', 'Vídeo con voz y subtítulos', 'De cada publicación, un vídeo vertical'],
      preparar: async h => { await h.cerrarTodo(); await h.v(() => { document.querySelector('#cmCard_0').scrollIntoView({ block: 'start' }); window.scrollBy(0, -80); }); await h.mover(700, 400, 10); },
      segs: [
        { t: 'De cada publicación, Chispa te hace también un vídeo vertical, para historias, reels o TikTok.', voz: 'De cada publicación, Chispa te hace también un vídeo vertical, para historias, rils o TikTok.',
          a: async h => { await h.clic(`${card(0)} button[onclick^="cmExportar"]`, { despues: 1200 }); } },
        { t: 'Lleva voz en off de la inteligencia artificial y subtítulos palabra a palabra. Y lo que dice, lo puedes cambiar.',
          a: async h => { await h.resaltar('#cmBox .cm-li', 2200); await h.resaltar('#ciaGuion', 1600); } },
        { t: 'Pulsas «Descargar vídeo vertical», y Chispa lo graba en un momento.',
          a: async h => { h._vid = await grabarVideo(h, true, 2500); } },
        { t: 'Así queda. Escúchalo.', a: async h => { await h.cerrarTodo(); await reproducirVideo(h, PREGEN('largo')); }, pausa: 0.5 },
      ],
    },
    {
      id: 'cliente', rotulo: ['7', 'Así lo ve tu cliente', 'Y publicar en todas tus redes'],
      preparar: async h => { await h.cerrarTodo(); await h.panel('asistente'); await h.v(() => document.querySelector('#cmCard_0 .cm-acts').scrollIntoView({ block: 'center' })); },
      segs: [
        { t: 'Antes de publicar, pulsas «Así lo ve tu cliente».', a: async h => { await h.clic(`${card(0)} button:has-text("Así lo ve tu cliente")`, { despues: 1200 }); } },
        { t: 'Y ves la publicación tal como saldrá en cada sitio: Instagram, con sus historias y sus reels, TikTok, Facebook, WhatsApp, Google y YouTube.',
          voz: 'Y ves la publicación tal como saldrá en cada sitio: Instagram, con sus historias y sus rils, TikTok, Facebook, WhatsApp, Google y YouTube.',
          a: async h => { await h.mover(700, 500); for (const y of [520, 1100, 1700, 2300]) { await h.scrollSuave('#cmBox', y); await h.esperar(700); } } },
        { t: 'Para publicar, eliges las redes y pulsas un botón. Esto es la demostración: aquí no se sube nada de verdad.',
          a: async h => { await h.cerrarTodo(); await h.v(() => window.scrollTo({ top: 0, behavior: 'smooth' })); await h.esperar(800); await h.clic('button:has-text("Ver demo de publicación")', { despues: 2500 }); await h.resaltar('#cmBox >> text=No se sube nada de verdad', 1800); } },
        { t: 'Cuando conectes tus cuentas y cada red dé su permiso, se publica solo, a su hora.', a: async h => { await h.mover(330, 420); await h.esperar(3500); }, pausa: 0.8 },
      ],
      despues: async h => { await h.cerrarTodo(); },
    },
    {
      id: 'calendario', rotulo: ['8', 'Calendario', 'Franjas, día entero y promo para llenar'],
      preparar: async h => { await h.cerrarTodo(); await h.panel('asistente'); },
      segs: [
        { t: 'En el calendario ves tu semana. Cada color es una red, y cada publicación dice si está en borrador, programada o publicada.',
          a: async h => { await h.pestana('Calendario'); await h.mover(760, 600); await h.rueda(330); } },
        { t: 'Ahora entiende franjas: una promoción de seis a nueve de la tarde, con varias historias repartidas, o un día entero.',
          a: async h => { await h.verEn('#main >> text=Promo 2x1 en mojitos'); await h.resaltar(h.p.locator('#main >> text=Promo 2x1 en mojitos').first(), 2600); } },
        { t: 'Con «Promo para llenar», Chispa la monta en tus horas flojas: historias, una publicación y un aviso en el estado de WhatsApp, todo con el botón «Reservar».',
          a: async h => { await h.scrollSuave(null, 0); await h.clic('#main button:has-text("Promo para llenar")', { despues: 1400 }); await h.mover(720, 450); await h.rueda(400, 12, 1400); } },
        { t: 'Y comprueba que no se pisa con nada. Pulsas «Crear la promo», y listo.',
          a: async h => { await h.verEn('text=Todo cuadrado'); await h.resaltar(h.p.locator('text=Todo cuadrado').first(), 1600); await h.clic('button:has-text("Crear la promo")', { despues: 1500 }); } },
        { t: 'También se lo pides con tus palabras: «promo el sábado todo el día», y la pone como día entero.',
          a: async h => { await h.cerrarTodo(); await h.scrollSuave(null, 0); await h.clic('#main button:has-text("Promo el sábado todo el día")', { despues: 1800 }); await h.mover(1050, 420); }, pausa: 0.8 },
      ],
    },
    {
      id: 'bandeja', rotulo: ['9', 'Comentarios y mensajes', 'Todo junto, con la respuesta preparada'],
      preparar: async h => { await h.cerrarTodo(); await h.panel('calendario'); },
      segs: [
        { t: 'En «Comentarios y DMs» tienes juntos los comentarios, los mensajes privados y las reseñas de todas tus redes.',
          a: async h => { await h.pestana('Comentarios'); await h.mover(760, 400); } },
        { t: 'Chispa les pone etiquetas, reserva, pregunta, queja, y te propone la respuesta.',
          a: async h => { await h.rueda(380); await h.resaltar(h.p.locator('#main .cp-it', { hasText: 'Toni Ferrer' }).first(), 2400); } },
        { t: 'Si alguien quiere reservar para ocho, la contestación ya lleva tu enlace de reservas.',
          a: async h => { await h.zoom('#main >> text=Para reservar mesa', 1.3); await h.esperar(2200); await h.sinZoom(); } },
        { t: 'Pero nada sale sin tu visto bueno: la envías con un toque, o la cambias.',
          a: async h => { await h.clic(h.p.locator('#main .cp-it', { hasText: 'Toni Ferrer' }).locator('button:has-text("Enviar")').first(), { despues: 1200 }); } },
        { t: 'Estos mensajes son de ejemplo. Cuando entras con tu negocio, ves los de verdad.',
          a: async h => { await h.scrollSuave(null, 0); await h.resaltar('#main >> text=Datos de EJEMPLO', 2200); } },
      ],
    },
    {
      id: 'resenas', rotulo: ['10', 'Reseñas', 'Contestadas en el idioma del cliente'],
      preparar: async h => { await h.cerrarTodo(); await h.panel('bandeja'); },
      segs: [
        { t: 'En Reseñas, Chispa junta las opiniones de Google, TripAdvisor y TheFork, y te propone una respuesta para cada una.',
          voz: 'En Reseñas, Chispa junta las opiniones de Google, TripAdvisor y de Fork, y te propone una respuesta para cada una.',
          a: async h => { await h.pestana('Reseñas'); await h.mover(760, 500); await h.rueda(420); } },
        { t: 'Contesta en el tono de tu negocio y en el idioma del cliente: si te escriben en inglés, responde en inglés.',
          a: async h => { await h.verEn('#main >> text=Lovely spot in Palma'); await h.resaltar('#main >> text=Hi Emma', 2600); } },
        { t: 'Las buenas se pueden contestar solas. Las negativas, nunca: Chispa te avisa para que las mires tú, con calma.',
          a: async h => { await h.scrollSuave(null, 0); await h.clic('#main button:has-text("Negativas")', { despues: 1400 }); } },
        { t: 'Estas reseñas son de ejemplo. Al conectar tu ficha de Google, trabaja con las de verdad.',
          a: async h => { await h.resaltar('#main >> text=Estás viendo reseñas de ejemplo', 2400); } },
      ],
    },
    {
      id: 'automatizaciones', rotulo: ['11', 'Automatizaciones', 'Lo que Chispa hace sola'],
      preparar: async h => { await h.cerrarTodo(); await h.panel('resenas'); },
      segs: [
        { t: 'En Automatizaciones decides lo que Chispa hace sola.', a: async h => { await h.pestana('Automatizaciones'); await h.mover(760, 450); } },
        { t: 'Por ejemplo: alguien comenta «CARTA» en tu publicación, y le llega por privado el enlace a tu carta.',
          a: async h => { await h.verEn('#main >> text=Palabra clave en un comentario', 'start'); await h.v(() => window.scrollBy({ top: -100, behavior: 'smooth' })); await h.resaltar(h.p.locator('#main >> text=Palabra clave en un comentario').first(), 2400); } },
        { t: 'Las reseñas de cuatro y cinco estrellas se pueden contestar solas. Las negativas, nunca: te avisa para que las veas tú.',
          a: async h => { await h.verEn('#main >> text=Reseña nueva', 'start'); await h.v(() => window.scrollBy({ top: -100, behavior: 'smooth' })); await h.resaltar(h.p.locator('#main >> text=Reseña nueva').first(), 2400); } },
        { t: 'Te recuerda publicar si no tienes nada programado, y te manda un resumen cada semana.',
          a: async h => { await h.mover(760, 520); await h.rueda(700, 16, 1800); } },
        { t: 'Con tu cuenta, todo esto lo hace el servidor, aunque tengas la app cerrada.',
          a: async h => { await h.scrollSuave(null, 0); await h.resaltar('#main >> text=las ejecuta el servidor', 2200); } },
      ],
    },
    {
      id: 'anuncios', rotulo: ['12', 'Anuncios', 'Con un tope que nunca se pasa'],
      preparar: async h => { await h.cerrarTodo(); await h.panel('automatizaciones'); },
      segs: [
        { t: 'En Anuncios preparas una campaña para Instagram y Facebook, o para las búsquedas de Google.',
          a: async h => { await h.pestana('Anuncios'); await h.resaltar('#main select >> nth=0', 1800); } },
        { t: 'Eliges el objetivo, el texto, el presupuesto al día, cuántos días, y la zona alrededor de tu local.',
          a: async h => { await h.mover(760, 520); await h.rueda(500, 14, 1600); } },
        { t: 'Y Chispa te dice el tope: nunca se gasta ni un euro más de lo que pones.',
          a: async h => { await h.verEn('#main >> text=Ni un euro más'); await h.resaltar(h.p.locator('#main >> text=Ni un euro más').first(), 2400); } },
        { t: 'En la demostración solo se simula. Con tu cuenta conectada, la campaña se crea en pausa, y la lanzas tú cuando quieras.',
          a: async h => { await h.clic('#main button:has-text("Simular")', { despues: 1500 }); }, pausa: 0.6 },
      ],
    },
    {
      id: 'estadisticas', rotulo: ['13', 'Estadísticas', 'El día a día, con consejos'],
      preparar: async h => { await h.cerrarTodo(); await h.panel('anuncios'); },
      segs: [
        { t: 'En Estadísticas ves el día a día: alcance, visualizaciones, interacciones y seguidores. Y de Google, cuánta gente pide cómo llegar o te llama.',
          a: async h => { await h.pestana('Estadísticas'); await h.mover(760, 400); await h.rueda(250); } },
        { t: 'Estas cifras son de ejemplo, y lo pone bien claro. Con tus redes conectadas, el servidor las recoge solo cada mañana.',
          a: async h => { await h.resaltar('#main >> text=Cifras de EJEMPLO', 2400); } },
        { t: 'Lo mejor son los consejos hechos con tus datos: tus días fuertes, y qué hacer para que te vea más gente.',
          a: async h => { await h.verEn('#main >> text=Consejos con tus datos', 'start'); await h.v(() => window.scrollBy({ top: -100, behavior: 'smooth' })); await h.resaltar(h.p.locator('#main >> text=Tus días fuertes').first(), 2400); } },
        { t: 'Y los de Instagram sí son reales: El Paraíso tiene hoy mil doscientos seis seguidores.',
          a: async h => { await h.verEn('#main >> text=DATO REAL'); await h.zoom('#main >> text=DATO REAL', 1.3); await h.esperar(2000); await h.sinZoom(); } },
      ],
    },
    {
      id: 'estudio', ctx: 'b', rotulo: ['14', 'Estudio para creadores', 'Miniseries y guiones con IA'],
      preparar: async h => { await h.cerrarTodo(); await h.v(() => { vista('panel'); window.scrollTo(0, 0); }); await h.mover(1100, 120, 10); },
      segs: [
        { t: 'Para creadores de contenido, y para negocios que quieren hacer vídeos, está el Estudio para creadores.',
          a: async h => { await h.clic('#segC', { despues: 1200 }); await h.clic('#estudioApp button:has-text("Miniserie con IA")', { despues: 900 }); } },
        { t: 'Le dices un tema, por ejemplo: recetas de café para hacer en casa. Y la inteligencia artificial escribe una miniserie, episodio a episodio, con el gancho de cada uno.',
          a: async h => { await h.escribir('#serTema', 'Recetas de café para hacer en casa', 50); await h.clic('#estudioApp button:has-text("Escribir la serie")', { despues: 500 }); await h.p.waitForFunction(() => /EPISODIO 1/i.test(document.getElementById('estudioApp').innerText), null, { timeout: 60000 }).catch(() => { }); await h.verEn('#estudioApp >> text=EPISODIO 1', 'start').catch(() => { }); await h.v(() => window.scrollBy({ top: -160, behavior: 'smooth' })); await h.mover(760, 500); await h.rueda(400, 12, 1500); } },
        { t: 'Luego la pasas al calendario: entra como borrador, con fecha y hora, esperando a que grabes cada vídeo.',
          a: async h => { await h.clic('#estudioApp button:has-text("Pasar la serie al calendario")', { despues: 1500 }); } },
        { t: 'Viene en los planes Pro y Agencia, y escribe en el idioma que elijas.',
          a: async h => { await h.resaltar('#estudioApp >> text=Borrador (falta el vídeo) >> nth=0', 1600); await h.clic('#estudioApp button:has-text("Miniserie con IA")', { despues: 900 }); await h.scrollSuave(null, 0); await h.resaltar('#estudioApp >> text=IA activada', 2000); } },
      ],
      despues: async h => { await h.v(() => vista('panel')); },
    },
    {
      id: 'crecer', rotulo: ['15', 'Crecer', 'Cómo conseguir más clientes desde las redes'],
      preparar: async h => { await h.cerrarTodo(); await h.panel('asistente'); },
      segs: [
        { t: 'En «Crecer» tienes una guía para conseguir más clientes desde las redes, hecha para tu tipo de negocio.',
          a: async h => { await h.pestana('Crecer'); await h.resaltar('.cr-intro', 2000); } },
        { t: 'Cada consejo dice de dónde sale: si lo dice la propia red, si lo mide un estudio, o si es una opinión razonada.',
          a: async h => { await h.resaltar(h.p.locator('#main >> text=OFICIAL').nth(1), 2200); } },
        { t: 'Cómo hacer un vídeo que enganche, cuánto publicar, a qué hora, y qué no hacer para que no te penalicen.',
          a: async h => { await h.clic('#main button:has-text("Mejores horas")', { despues: 1500 }); await h.clic('#main button:has-text("No te penalicen")', { despues: 1300 }); }, pausa: 0.6 },
      ],
    },
    {
      id: 'tour', rotulo: ['16', 'Visita guiada', '«Ver cómo funciona»'],
      preparar: async h => { await h.cerrarTodo(); await h.v(() => { vista('landing'); window.scrollTo(0, 0); }); await h.mover(700, 500, 10); },
      segs: [
        { t: 'Y si quieres que la propia Chispa te lo enseñe, pulsa «Ver cómo funciona».', a: async h => { await h.clic('#ctFab', { despues: 1200 }); } },
        { t: 'Eliges un tipo de negocio, un restaurante, una peluquería, un gimnasio, y te lleva paso a paso por la app de verdad, con un negocio de ejemplo.',
          a: async h => { await h.mover(650, 400); await h.mover(920, 520); await h.clic('.ct-card[data-id="restaurante"]', { despues: 2500 }); } },
        { t: 'En cada paso te señala qué es cada cosa. Vas con «Siguiente», a tu ritmo.',
          a: async h => { await h.clic('#ctNext', { despues: 2200 }); await h.clic('#ctNext', { despues: 2000 }); }, pausa: 0.8 },
      ],
      despues: async h => { await h.v(() => { try { document.getElementById('ctClose').click(); } catch (e) { } }); },
    },
    {
      id: 'plan', ctx: 'b', rotulo: ['17', 'Mi plan', 'Tu prueba, tu uso y la baja'],
      preparar: async h => { await h.cerrarTodo(); await h.panel('asistente'); },
      segs: [
        { t: 'En «Mi plan» ves tu plan, los días de prueba que te quedan, y lo que llevas usado este mes.',
          a: async h => { await h.pestana('Mi plan'); await h.ocultarTexto('correo .*@'); await h.esperar(300); await h.resaltar('#main .card >> nth=0', 2000); await h.resaltar(cardTxt(h, 'Lo que llevas usado'), 1800); } },
        { t: 'Puedes cambiar de plan cuando quieras. De momento el pago con tarjeta no está activado, así que la prueba no te cobra nada.',
          a: async h => { await h.ocultarTexto('correo .*@'); await h.verEn('#main >> text=Elegir plan'); await h.resaltar(cardTxt(h, 'Elegir plan'), 1800); await h.resaltar('#main >> text=El pago con tarjeta todavía no está activado', 1800); } },
        { t: 'Y sin permanencia: te das de baja cuando quieras, y se borran todos tus datos.',
          a: async h => { await h.ocultarTexto('correo .*@'); await h.verEn('#main button:has-text("Darme de baja")'); await h.resaltar('#main button:has-text("Darme de baja")', 2000); }, pausa: 0.6 },
      ],
    },
    {
      id: 'cierre', entrada: 300,
      preparar: async h => { await h.v(() => window.__V.cursorVisible(false)); await h.tarjeta(CIERRE); await h.esperar(900); },
      segs: [
        { t: 'Chispa: para tu negocio o para tu canal, y en tu idioma.' },
        { t: 'Cuando conectes tus cuentas y cada red dé su permiso, se publica solo.' },
        { t: 'Pruébalo 14 días gratis, sin tarjeta. Tú atiendes tu negocio; Chispa llena tus redes.', voz: 'Pruébalo catorce días gratis, sin tarjeta. Tú atiendes tu negocio; Chispa llena tus redes.', pausa: 1.6 },
      ],
      salida: 1.0,
    },
  ],
};
